name: awaitws
description: Simplify WebSockets by allowing you to await upon requests.
version: 1.0.0
homepage: https://github.com/VolticFroogo/await-ws-dart

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  mutex: ^1.1.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
